import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

// Configuración de la fuente Outfit
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  // weights: ["300", "400", "600", "700"], // Define los pesos que planeas usar
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Puedes agregar otras configuraciones en el head si es necesario */}
      </head>
      <body className={`${outfit.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
